# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: EVA Open Targets pipelines

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install native packages
      run: |
        sudo apt update
        sudo apt -y install samtools bcftools parallel libbz2-dev liblzma-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py install
    - name: Install Nextflow
      run: |
        mkdir /tmp/nextflow && cd /tmp/nextflow
        wget -qO- get.nextflow.io | bash
        echo "/tmp/nextflow" >> $GITHUB_PATH
        cd -

    - name: Unit tests
      run: python -m pytest --cov=cmat -k "not integration"

    - name: Integration tests
      run: python -m pytest --cov=cmat --cov-append tests -k integration

    - name: End-to-end test of evidence string generation pipeline
      run: bash tests/eva_cttv_pipeline/evidence_string_generation/test_pipeline.sh
    
    - name: Upload the coverage data to Coveralls
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls
